### PR TITLE
Add RHEL7

### PR DESCRIPTION
**Pull request by mrbusche**
I plan on adding 3 more for rhel, 7-minimal, 8, and 8-minimal and also centos, but not sure of the format yet. Would you prefer a copy of `GenericJsonPathChecker.kt` that accepts a LinkedHashMap? That seems like the best way, but I'm not super familiar with Kotlin. I couldn't figure out a way to have `GenericJsonPathChecker.kt` work with the response I'm getting.

I'll also clean up those comments at the end of the file when I write the others.

### CODE REVIEW

**Comment by jonathanlermitage** [comment]
@mrbusche I think we can keep simple classes. `RHEL7Checker` implementation is good for me :+1:.  
If needed, I will do some refactoring later.

**Comment by mrbusche** [comment]
Awesome! I'll add the others tonight and clean things up

**Comment by mrbusche** [comment]
Should be good to go now. It's CentOS that has versions 7 and 8 out now, not RHEL.

**Comment by jonathanlermitage** [comment]
Perfect, thx!

**Pull request merged**
